name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    example:
        description: An example command
        usage: /<command>

permissions: {}