name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.17


main: ${mainClass}

commands:
  sidebar:
    description: Sets which field displays on your sidebar
    usage: /<command> {clear|display|shuffle} <Name of board to display>
  sbar-reload:
    description: Reloads the config
    permission: sidebar.reload
    usage: /<command>
  sbar-reshuffle:
    description: Reshuffles the sidebar
    permission: sidebar.reshuffle
    usage: /<command>

permissions:
  sidebar.reload:
    permission:
      default: op
  sidebar.reshuffle:
    permission:
      default: op